{% set version = '0.99.31.3' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-memisc
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/memisc_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/memisc/memisc_{{ version }}.tar.gz
  sha256: 054bd04fdbb8523b81ec3958084b4493bf7657f7f2326b414a98e9a8f68b786a

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-mass
    - r-data.table
    - r-jsonlite
    - r-lattice
    - r-yaml
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-mass
    - r-data.table
    - r-jsonlite
    - r-lattice
    - r-yaml

test:
  commands:
    - $R -e "library('memisc')"           # [not win]
    - "\"%R%\" -e \"library('memisc')\""  # [win]

about:
  home: http://memisc.elff.eu,https://github.com/melff/memisc/
  license: GPL-2.0-only
  summary: An infrastructure for the management of survey data including value labels, definable
    missing values, recoding of variables, production of code books, and import of (subsets
    of) 'SPSS' and 'Stata' files is provided. Further, the package allows to produce
    tables and data frames of arbitrary descriptive statistics and (almost) publication-ready
    tables of regression model estimates, which can be exported to 'LaTeX' and HTML.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
